title: aoi blog
description: Hello!\[. _ .]/ Welcome back my blog! 
theme: jekyll-theme-minimal
author: aoi
timezone: Asia/Tokyo

# 既存の設定の下に追記
header_pages:
  - index.md
  - about.md

# ソーシャルリンクなどを出したい場合（テーマによって対応が異なります）
github_username: 115aoi
#twitter_username: TwitterID
